networks:
  inception: {}

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
      - mariadb
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/osarsari/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/osarsari/data/wordpress